### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by ckaak** [Yuzuki616/V2bX#27]
**描述该错误**
 systemd[1]: Started V2bX Service.
 V2bX[2818]: V2bX v0.0.6 (A V2board backend based on Xray-core)
 V2bX[2818]: Core Version: 1.5.10
 V2bX[2818]: Start the panel..
 V2bX[2818]: [Warning] core: Xray 1.5.10 started
 V2bX[2818]: run nodes error: start node controller error: common/protocol: Account missing
 V2bX[2818]: panic: run nodes error: start node controller error: common/protocol: Account missing
 V2bX[2818]: goroutine 1 [running]:
 V2bX[2818]: log.Panicf({0x21f93ed?, 0x1?}, {0xc0011b7f28?, 0xc0009bb380?, 0x0?})
 V2bX[2818]:         log/log.go:395 +0x67
 V2bX[2818]: main.main()
 V2bX[2818]:         github.com/Yuzuki616/V2bX/main.go:90 +0x2ae
 systemd[1]: V2bX.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
 systemd[1]: V2bX.service: Failed with result 'exit-code'.
 systemd[1]: V2bX.service: Service RestartSec=10s expired, scheduling restart.
 systemd[1]: V2bX.service: Scheduled restart job, restart counter is at 13.

**复现**
我填了下面四个选项以后，无法启动，我这里找不到面板类型的参数，不知道和XRAYR有什么不一样的。
      ApiHost: "https://xxxxx.com"
      ApiKey: "x"
      NodeID: x
      NodeType: Shadowsocks# Node type: V2ray, Shadowsocks, Trojan

**环境和版本**
 - 系统 [例如：Debian 11]
 - 架构 [例如：AMD64]
 - 面板 [例如：V2board]
 - 协议 [例如：Shadowsocks]
 - 版本 [例如：最新版本]
 - 部署方式 [例如：一键脚本]

**Comment by Yuzuki616** [comment]
节点配置截图发来看看，敏感信息打一下碼

**Comment by ckaak** [comment]
![Image 001](https://user-images.githubusercontent.com/84608691/196295365-e8fc0665-93f2-4359-96ee-e6cf5d65dc43.png)
![Image 002](https://user-images.githubusercontent.com/84608691/196295370-c8d697d9-eebb-4477-a22d-7c0688365e7b.png)

我就填了下面四个参数。

**Comment by ckaak** [comment]
我试了试trojan，也是无法启动，ssl证书也是配置正确的，制定了ssl目录文件。感觉是api能获取到用户，但就是内核无法启动。

systemd[1]: Started V2bX Service.
V2bX[7808]: V2bX v0.0.6 (A V2board backend based on Xray-core)
V2bX[7808]:  Core Version: 1.5.10
V2bX[7808]:  Start the panel..
V2bX[7808]:  [Warning] core: Xray 1.5.10 started
 V2bX[7808]: 2022/10/18 07:13:21 [Trojan: 2] Added 41 new users
 V2bX[7808]: panic: runtime error: invalid memory address or nil pointer dereference
 V2bX[7808]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe73780]
 V2bX[7808]: goroutine 1 [running]:
 V2bX[7808]: github.com/Yuzuki616/V2bX/core/app/dispatcher.(*Limiter).AddInboundLimiter(0xc000012aa0, {0xc000d25090, 0x10}, 0xc000d239e0, {0xc000149500, 0x29, 0x203000?})
 V2bX[7808]:         github.com/Yuzuki616/V2bX/core/app/dispatcher/limiter.go:53 +0x180
 V2bX[7808]: github.com/Yuzuki616/V2bX/core.(*Core).AddInboundLimiter(...)
 V2bX[7808]:         github.com/Yuzuki616/V2bX/core/inbound.go:33
 V2bX[7808]: github.com/Yuzuki616/V2bX/node.(*Node).Start(0xc000afa640)
 V2bX[7808]:         github.com/Yuzuki616/V2bX/node/node.go:71 +0x358
 V2bX[7808]: main.startNodes({0xc0000121a0, 0x1, 0xc000a5ac40?}, 0xc000701bc0)
 V2bX[7808]:         github.com/Yuzuki616/V2bX/main.go:65 +0x10a
 V2bX[7808]: main.main()
 V2bX[7808]:         github.com/Yuzuki616/V2bX/main.go:88 +0x269
 systemd[1]: V2bX.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
 systemd[1]: V2bX.service: Failed with result 'exit-code'.
systemd[1]: V2bX.service: Scheduled restart job, restart counter is at 14.
systemd[1]: Stopped V2bX Service.
systemd[1]: Started V2bX Service.
V2bX[7814]: V2bX v0.0.6 (A V2board backend based on Xray-core)
V2bX[7814]:Core Version: 1.5.10
V2bX[7814]: Start the panel..
V2bX[7814]:  [Warning] core: Xray 1.5.10 started
V2bX[7814]:  [Trojan: 2] Added 41 new users
V2bX[7814]: panic: runtime error: invalid memory address or nil pointer dereference
V2bX[7814]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe73780]
V2bX[7814]: goroutine 1 [running]:
V2bX[7814]: github.com/Yuzuki616/V2bX/core/app/dispatcher.(*Limiter).AddInboundLimiter(0xc00012e228, {0xc000130880, 0x10}, 0xc000121da0, {0xc000185500, 0x29, 0x203000?})
V2bX[7814]:         github.com/Yuzuki616/V2bX/core/app/dispatcher/limiter.go:53 +0x180
V2bX[7814]: github.com/Yuzuki616/V2bX/core.(*Core).AddInboundLimiter(...)
V2bX[7814]:         github.com/Yuzuki616/V2bX/core/inbound.go:33
V2bX[7814]: github.com/Yuzuki616/V2bX/node.(*Node).Start(0xc00003b180)
V2bX[7814]:         github.com/Yuzuki616/V2bX/node/node.go:71 +0x358
V2bX[7814]: main.startNodes({0xc000012e48, 0x1, 0xc000a8f810?}, 0xc000134940)
V2bX[7814]:         github.com/Yuzuki616/V2bX/main.go:65 +0x10a
V2bX[7814]: main.main()
V2bX[7814]:         github.com/Yuzuki616/V2bX/main.go:88 +0x269
systemd[1]: V2bX.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: V2bX.service: Failed with result 'exit-code'.

附上完整的配置
[config.txt](https://github.com/Yuzuki616/V2bX/files/9805118/config.txt)

**Comment by Yuzuki616** [comment]
新版本已修复

**Comment by katyshawn922** [comment]
> 新版本已修复

好像没有，，还是一样的问题
------------------------------------------------------
V2bX[78822]: 2022/10/18 10:03:28 Start V2bX...
V2bX[78822]: 2022/10/18 10:03:28 Core Version: 1.6.0
V2bX[78822]: 2022/10/18 10:03:28 [Warning] core: Xray 1.6.0 started
V2bX[78822]: 2022/10/18 10:03:29 [Warning] transport/internet/tcp: accepting PROXY protocol
V2bX[78822]: 2022/10/18 10:03:29 run nodes error: common/protocol: Account missing
V2bX[78822]: panic: run nodes error: common/protocol: Account missing
V2bX[78822]: goroutine 1 [running]:
V2bX[78822]: log.Panicf({0x222b87f?, 0xc000c28198?}, {0xc001077f28?, 0xc000084730?, 0xc000c31d10?})
V2bX[78822]:         log/log.go:395 +0x67
V2bX[78822]: main.main()
V2bX[78822]:         github.com/Yuzuki616/V2bX/main.go:53 +0x3fc
systemd[1]: V2bX.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: V2bX.service: Failed with result 'exit-code'.
systemd[1]: V2bX.service: Scheduled restart job, restart counter is at 1.
systemd[1]: Stopped V2bX Service.

**Comment by Yuzuki616** [comment]
之前似乎变动没推上去，半夜重新推了一次，要是用了之前的的话重新更新一下吧

**Comment by Yuzuki616** [comment]
ss2022暂时不打算支持，v2b支持的时候我这边再考虑支持

**Comment by ckaak** [comment]
> ss2022暂时不打算支持，v2b支持的时候我这边再考虑支持

好尴尬。V2B那边说等后端。。。
