### ISSUE TITLE
is support vless in v2board?

### ISSUE THREAD

**Issue by miladrajabi2002** [Yuzuki616/V2bX#42]
can i creat vless config ?

**Comment by Yuzuki616** [comment]
yes. please see config.yml.example

**Comment by miladrajabi2002** [comment]
where is config.yml.example??
pleas help me to create vless with v2board and https://github.com/Yuzuki616/V2bX

**Comment by Yuzuki616** [comment]
https://github.com/Yuzuki616/V2bX/blob/master/example/config.yml.example

**Comment by miladrajabi2002** [comment]
i tested and give me vmess not vless

**Comment by Yuzuki616** [comment]
you should go to v2board

**Comment by miladrajabi2002** [comment]
what do you mean?
v2board not any config for vless ?!
can you help me?

**Comment by miladrajabi2002** [comment]
why close this issue?
