### ISSUE TITLE
对接v2b报错是需要修改v2b的config接口吗？

### ISSUE THREAD

**Issue by hc4620303** [Yuzuki616/V2bX#5]
![image](https://user-images.githubusercontent.com/22239425/173220988-64e79c74-b162-4725-9be4-ab3fb53e12da.png)

**Comment by Yuzuki616** [comment]
用错版本了吧

**Comment by hc4620303** [comment]
我现在使用的最新的V2B

**Comment by hc4620303** [comment]
> 

原版的v2b没有远程限制IP和速率

**Comment by Yuzuki616** [comment]
我说v2bx，你这明显不是最新版本

**Comment by hc4620303** [comment]
我是刚刚git你的代码进行编译的

**Comment by Yuzuki616** [comment]
那是你编译的有问题或者拉错代码了，244行不可能会panic

**Comment by hc4620303** [comment]
我编译
![image](https://user-images.githubusercontent.com/22239425/173221469-6abd6100-c8bf-47ac-bece-3f087f763123.png)
老哥的可以成功运行- -！会不会是config接口的问题 因为这个报错感觉是接口相关的问题，之前使用这个老哥的user接口如果没用户也会报这个类似的错误
![image](https://user-images.githubusercontent.com/22239425/173221605-d37953fe-57af-4f97-bd88-d18008043785.png)
你这个是需要修改web端的config接口吗还是？

**Comment by Yuzuki616** [comment]
246行
``` go
if notParseNode {
			return nil, nil
		}
```
这哪来的下标越界，能不能别乱改，你这让我怎么看调试信息

**Comment by hc4620303** [comment]
![image](https://user-images.githubusercontent.com/22239425/173221925-6accb848-255c-4c56-a98a-202a4af583fe.png)
一直有这一行 我只加了个打印 现在还原了

**Comment by hc4620303** [comment]
![image](https://user-images.githubusercontent.com/22239425/173222009-f0202c72-fee0-4f1e-a1c2-803bd8da932d.png)

**Comment by hc4620303** [comment]
`{"log":{"loglevel":"none","access":"access.log","error":"error.log"},"api":{"services":["HandlerService","StatsService"],"tag":"api"},"dns":{"servers":[]},"stats":{},"inbounds":[{"port":80,"protocol":"vmess","settings":{"clients":[]},"sniffing":{"enabled":false,"destOverride":["http","tls"]},"streamSettings":{"network":"ws","wsSettings":{"path":"\/","headers":{"Host":"www.baidu.com"}}},"tag":"proxy"},{"listen":"127.0.0.1","port":1,"protocol":"dokodemo-door","settings":{"address":"0.0.0.0"},"tag":"api"}],"outbounds":[{"protocol":"freedom","settings":{"domainStrategy":"UseIP"}},{"protocol":"blackhole","settings":{},"tag":"block"}],"routing":{"rules":[{"type":"field","inboundTag":"api","outboundTag":"api"}]},"policy":{"levels":{"0":{"handshake":4,"connIdle":300,"uplinkOnly":5,"downlinkOnly":30,"statsUserUplink":true,"statsUserDownlink":true}}}}`

这是我的config接口返回的json

**Comment by Yuzuki616** [comment]
问题出在242行，修好了

**Comment by hc4620303** [comment]
可以了
