### ISSUE TITLE
设备限速无效

### ISSUE THREAD

**Issue by hc4620303** [Yuzuki616/V2bX#6]
老哥 设备限制我改yml配置文件 DeviceLimit参数为1  但是还是可以同时连接多台设备 我连接了3台设备都能正常访问网络

第二个就是
![image](https://user-images.githubusercontent.com/22239425/173225471-049f4cc6-b34c-4f6f-924d-4311c733369e.png)
这两个功能如何实现啊 我在user接口中增加device_limit参数和speed_limit参数 好像也没有用

**Comment by hc4620303** [comment]
我在user接口中添加了
![image](https://user-images.githubusercontent.com/22239425/173225664-bb4a0f12-b6b6-4556-9b58-7061fee40cc9.png)
这两个参数 程序也取到了 也正常到limiter了
![image](https://user-images.githubusercontent.com/22239425/173225698-5e064daa-23d2-4d68-a1a9-ef2d59a60e9e.png)

**Comment by hc4620303** [comment]
老哥 有没得文档啊 或者 你自己的web端 我参考一下 不然一直找你 不好得

**Comment by hc4620303** [comment]
![image](https://user-images.githubusercontent.com/22239425/173230108-91d363d2-3668-4ba7-8454-93a4bd764c5f.png)
这个地方一直走不进去

**Comment by Yuzuki616** [comment]
limiter的bug已修复。关于todo中的那两个功能，我不打算通过修改v2board的api实现，请自行研究

**Comment by hc4620303** [comment]
老哥 BUG又来了 新版本 没网-  -

**Comment by Yuzuki616** [comment]
这就是你的问题了，我这边一直在用着，完全没问题

**Comment by hc4620303** [comment]
真不是我的问题 你上一个版本和misakano的版本都有网  唯独你的新版本没有网络

**Comment by Yuzuki616** [comment]
日志拿来看看

**Comment by hc4620303** [comment]
知道原因了 是
![image](https://user-images.githubusercontent.com/22239425/173285041-b3a6673d-f501-4ed4-aa27-ad0038209e4a.png)
没有转换
![image](https://user-images.githubusercontent.com/22239425/173285064-e901119f-a9d3-465d-807d-a15d90e65dde.png)

**Comment by hc4620303** [comment]
如何转换呢

**Comment by hc4620303** [comment]
![image](https://user-images.githubusercontent.com/22239425/173285801-3157aa92-b6e6-49d0-848f-67fb545a57c9.png)
放这里有问题没

**Comment by Yuzuki616** [comment]
你是在改v2b下发limit吧，我这里预留DeviceLimit和Speed Limit不是这个用途，你非要这样用那就自己解决问题，这两个字段将会在下个版本移除

**Comment by hc4620303** [comment]
那是啥用啊 那你todo上的
![image](https://user-images.githubusercontent.com/22239425/173287524-54f82995-77c0-431e-84d5-af2f252818a3.png)
这两个功能现在实现没有嘞

**Comment by hc4620303** [comment]
我没有看到关于这两个功能的使用说明 哭笑~

**Comment by Yuzuki616** [comment]
前者将使用类似soga的redis方案
后者则是将特定用户的limit写入配置文件
以上均未实现，不然为什么叫todo
另外，本项目不考虑增加需要修改v2b实现的功能
